name: Docker Build and Push to zjf2610

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: "zjf2610"        # 指定目标Docker Hub用户名
  IMAGE_NAME: "opensips-custom"        # 镜像名称（自定义）
  OPENSIPS_VERSION: "3.5.4"            # OpenSIPS版本

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}  # 直接使用环境变量
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # 需配置Token密钥

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.OPENSIPS_VERSION }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            OPENSIPS_VERSION=${{ env.OPENSIPS_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
