name: Build and Deploy OpenSIPS Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置 QEMU，以支持多架构构建
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # 设置 Docker Buildx，以支持高级构建功能
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 登录 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: zjf2610/opensips:latest
          build-args: |
            MODULES=db_mysql,mi_http,httpd,maxfwd,sl,rr,tm
