name: Build and Push OpenSIPS Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: "zjf2610"
  IMAGE_NAME: "opensips-custom"
  OPENSIPS_MAJOR: "3.5"
  OPENSIPS_MODULES: "db_mysql,mi_http,httpd,maxfwd,sl,rr,tm"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.OPENSIPS_MAJOR }}
            ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          build-args: |
            OPENSIPS_MAJOR=${{ env.OPENSIPS_MAJOR }}
            OPENSIPS_MODULES=${{ env.OPENSIPS_MODULES }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

          
